# Generated by Django 2.0.1 on 2018-05-06 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('posts', '0003_auto_20180506_0002'),
        ('likes', '0002_auto_20180505_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='target',
        ),
        migrations.AddField(
            model_name='like',
            name='target_entity',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='entities.Entity'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
