# Generated by Django 2.0.1 on 2018-06-05 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20180603_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationcommentliked',
            name='notification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.Notification'),
        ),
        migrations.AlterField(
            model_name='notificationfollowed',
            name='notification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.Notification'),
        ),
        migrations.AlterField(
            model_name='notificationpostcommented',
            name='notification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.Notification'),
        ),
        migrations.AlterField(
            model_name='notificationpostliked',
            name='notification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.Notification'),
        ),
    ]
