# Generated by Django 2.0.1 on 2018-02-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180223_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='relationships', through='users.Follow', to='users.UserProfile'),
        ),
    ]
