# Generated by Django 2.0.1 on 2018-02-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180224_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
