# Generated by Django 2.0.1 on 2018-02-28 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180228_2116'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='follow',
            managers=[
            ],
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
    ]
