# Generated by Django 2.0.1 on 2018-04-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180228_2252'),
    ]

    database_operations = [
        migrations.AlterModelTable('Follow', 'follows_follow')
    ]

    state_operations = [
        migrations.DeleteModel('Follow')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
