# Generated by Django 2.0.1 on 2018-05-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('POST', 'Post'), ('COMMENT', 'Comment')], max_length=7)),
            ],
        ),
    ]
