# Generated by Django 2.0.1 on 2018-04-08 21:54

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180408_2153')
    ]

    state_operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('from_person',
                 models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='sender',
                                   to=settings.AUTH_USER_MODEL)),
                ('to_person', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='target',
                                                to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'db_table': 'follows_follow',
            },
            bases=(models.Model,),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
