# Generated by Django 2.0.1 on 2018-05-31 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20180531_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='post',
            new_name='target',
        ),
    ]
