# Generated by Django 2.0.1 on 2018-05-06 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180505_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='target',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='entities.Entity'),
        ),
    ]
