# Generated by Django 2.0.1 on 2018-04-03 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
        ('posts', '0005_auto_20180310_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='target',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='likes.Target'),
        ),
    ]
