# Generated by Django 2.0.1 on 2018-04-03 21:36

from django.db import migrations


def create_targets(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    Target = apps.get_model('likes', 'Target')

    for post in Post.objects.all():
        target = Target()
        target.save()
        post.target = target
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_target'),
    ]

    operations = [
        migrations.RunPython(create_targets),
    ]
