# Generated by Django 2.0.1 on 2018-04-04 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180403_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='target',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='likes.Target'),
        ),
    ]
